(() => {
'use strict';
const KEY='moneyflow-v3', $=id=>document.getElementById(id), now=new Date(), today=now.toISOString().slice(0,10), currentMonth=today.slice(0,7);
const defaults=[['Food & Drinks','expense'],['Transportation','expense'],['Family','expense'],['Housing','expense'],['Utilities','expense'],['Shopping','expense'],['Health','expense'],['Education','expense'],['Salary','income'],['Bonus','income']];
const blank={transactions:[],categories:defaults.map(([name,type])=>({name,type,createdAt:new Date().toISOString()})),budgets:[],loans:[],goals:[],reportMonth:currentMonth,currentType:'expense',settings:{theme:'light',syncUrl:'',syncRevision:'',lastSynced:''}};
let state=load(), syncing=false;
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');return normalize({...blank,...raw,settings:{...blank.settings,...(raw.settings||{})}})}catch(_){return structuredClone(blank)}}
function normalize(s){s.transactions=Array.isArray(s.transactions)?s.transactions:[];s.categories=Array.isArray(s.categories)&&s.categories.length?s.categories:structuredClone(blank.categories);s.budgets=Array.isArray(s.budgets)?s.budgets:[];s.loans=Array.isArray(s.loans)?s.loans:[];s.reportMonth=/^\d{4}-\d{2}$/.test(s.reportMonth)?s.reportMonth:currentMonth;s.transactions=s.transactions.map(t=>{const x={...t,amount:num(t.amount),category:t.category||'General'};const c=String(x.category).toLowerCase();if(x.type==='loan'||c==='loan'||c==='loan received'){x.type='income';x.category='Loan';x.loanId=x.loanId||uid('loan');}if(c==='loan repayment'||c==='loan payback'){x.type='expense';x.category='Loan Repayment';}return x});rebuildLoans(s);return s}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(_){toast('Could not save locally')}}
function uid(p='id'){return `${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`} function num(v){return Number(String(v??'').replace(/,/g,''))||0} function money(v){return `${Math.round(num(v)).toLocaleString()} MMK`} function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))} function toast(m){const e=$('toast');e.textContent=m;e.classList.add('on');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('on'),2600)}
function rebuildLoans(s){s.transactions.filter(t=>t.loanId&&t.type==='income').forEach(t=>{if(!s.loans.some(l=>String(l.id)===String(t.loanId)))s.loans.push({id:t.loanId,name:t.note||'Loan',principal:num(t.amount),remaining:num(t.amount),date:t.date,note:t.note||'',createdAt:t.createdAt})});s.loans.forEach(l=>{const received=s.transactions.filter(t=>t.loanId&&String(t.loanId)===String(l.id)&&t.type==='income').reduce((a,t)=>a+num(t.amount),0),paid=s.transactions.filter(t=>t.loanId&&String(t.loanId)===String(l.id)&&t.type==='expense').reduce((a,t)=>a+num(t.amount),0);l.remaining=Math.max(0,received-paid);l.principal=received||num(l.principal)})}
function month(){return state.reportMonth} function txs(m=month()){return state.transactions.filter(t=>String(t.date||'').slice(0,7)===m)} function totals(list){return list.reduce((a,t)=>{if(t.type==='income')a.income+=num(t.amount);if(t.type==='expense')a.expense+=num(t.amount);if(t.type==='credit')a.credit+=num(t.amount);return a},{income:0,expense:0,credit:0})} function spend(m,n){return txs(m).filter(t=>t.type==='expense'&&!t.loanId&&String(t.category)===String(n)).reduce((a,t)=>a+num(t.amount),0)}
function budgetRows(m=month()){return state.budgets.filter(b=>b.month===m).map(b=>{const spent=spend(m,b.name),amount=num(b.amount),used=amount?spent/amount*100:0,remaining=amount-spent,overdue=Boolean(b.dueDate&&b.dueDate<today&&remaining>0);return {...b,spent,amount,used,remaining,overdue,near:used>=num(b.threshold||80),exceeded:spent>amount}}).sort((a,b)=>b.spent-a.spent)}
function show(id){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===id));document.querySelectorAll('.nav-btn').forEach(e=>e.classList.toggle('active',e.dataset.page===id))}
function setType(type){state.currentType=type;const titles={expense:'Add Expense',income:'Add Income',loan:'Loan received',payback:'Payback loan',credit:'Credit payment'};$('formTitle').textContent=titles[type];document.querySelectorAll('.tab').forEach(e=>e.classList.toggle('active',e.dataset.type===type));const loan=type==='payback';$('loanField').hidden=!loan;$('categoryField').hidden=loan;populate()}
function populate(){const type=state.currentType==='payback'?'expense':state.currentType;const cats=state.categories.filter(c=>c.type===type);$('category').innerHTML=(cats.length?cats:[{name:'General'}]).map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');$('budgetCategory').innerHTML=state.categories.filter(c=>c.type==='expense').map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')||'<option>General</option>';const loans=state.loans.filter(l=>l.remaining>0);$('loanSelect').innerHTML=loans.map(l=>`<option value="${esc(l.id)}">${esc(l.name)} (${money(l.remaining)})</option>`).join('')||'<option value="">No active loans</option>'}
function updateMonths(){const vals=new Set([month(),...state.transactions.map(t=>String(t.date||'').slice(0,7)),...state.budgets.map(b=>b.month)].filter(Boolean));$('monthSelect').innerHTML=[...vals].sort().map(m=>`<option value="${m}">${m}</option>`).join('');$('monthSelect').value=month()}
function render(){normalize(state);save();populate();updateMonths();const list=txs(), t=totals(list), net=t.income-t.expense-t.credit;$('homeIncome').textContent=money(t.income);$('homeExpense').textContent=money(t.expense);$('homeNet').textContent=money(net);$('homeMonth').textContent=month();$('focusMsg').textContent=net>=0?'You are within your cash flow.':'Spending is above income this month.';$('recentTransactions').innerHTML=state.transactions.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,6).map(rowTx).join('')||empty('No transactions yet');const rows=budgetRows(), total=rows.reduce((a,b)=>a+b.amount,0),spent=rows.reduce((a,b)=>a+b.spent,0);$('budgetTotal').textContent=money(total);$('budgetSpent').textContent=money(spent);$('budgetRemaining').textContent=money(total-spent);$('budgetUsedPct').textContent=`${total?Math.round(spent/total*100):0}%`;$('budgetAlerts').innerHTML=rows.map(alertRow).join('')||empty('No budget set for this month');$('budgetBreakdown').innerHTML=rows.map(budgetRow).join('')||empty('Add a budget to see category performance');renderFlow();renderTables();renderManagers();renderTheme();$('syncUrl').value=state.settings.syncUrl||'';$('budgetMonth').value=month();}
function empty(text){return `<div class="alert success"><strong>${esc(text)}</strong></div>`} function rowTx(t){const cls=t.type==='income'?'income-text':t.type==='expense'?'expense-text':'';return `<div class="list-item"><div><strong>${esc(t.category)}</strong><small>${esc(t.date||'')} · ${esc(t.note||t.type)}</small></div><span class="amount ${cls}">${t.type==='expense'?'-':'+'}${money(t.amount)}</span></div>`}function alertRow(b){let c='success',text='On track';if(b.exceeded){c='danger';text=`Exceeded by ${money(-b.remaining)}`}else if(b.near){c='warning';text=`Near limit · ${Math.round(b.used)}% used`}else if(b.overdue){c='warning';text=`Overdue · ${money(b.remaining)} left`}return `<div class="alert ${c}"><div><strong>${esc(b.name)}</strong><small>${money(b.spent)} of ${money(b.amount)}</small></div><span>${text}</span></div>`}function budgetRow(b){const p=Math.min(100,Math.round(b.used));return `<div class="budget-item"><div class="section-head"><strong>${esc(b.name)}</strong><span>${money(b.spent)} / ${money(b.amount)}</span></div><div class="progress"><span class="${p>=90?'bad':p>=b.threshold?'warn':''}" style="width:${p}%"></span></div><div class="section-head"><small>${p}% used</small><button class="danger-btn" type="button" data-delete-budget="${esc(b.id)}">Delete</button></div></div>`}
function renderFlow(){const months=[...new Set([...state.transactions.map(t=>String(t.date||'').slice(0,7)),...state.budgets.map(b=>b.month)])].filter(Boolean).sort().slice(-6);$('focusBI').innerHTML=months.map(m=>{const t=totals(txs(m)),b=state.budgets.filter(x=>x.month===m).reduce((a,x)=>a+num(x.amount),0);return `<div class="focus-item"><strong>${m}</strong><span>Budget ${money(b)} · Spent ${money(t.expense)} · Income ${money(t.income)}</span></div>`}).join('')||empty('No monthly data')}
function renderTables(){$('transactionRows').innerHTML=state.transactions.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(t.type)}</td><td>${esc(t.category)}</td><td>${esc(t.note||'-')}</td><td>${money(t.amount)}</td><td><button class="danger-btn" type="button" data-delete-tx="${esc(t.id)}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No transactions</td></tr>'}
function renderManagers(){$('categoryList').innerHTML=state.categories.map((c,i)=>`<div class="list-item"><span>${esc(c.name)} <small>${esc(c.type)}</small></span><button class="danger-btn" type="button" data-delete-cat="${i}">Delete</button></div>`).join('');$('budgetList').innerHTML=state.budgets.map(b=>`<div class="list-item"><div><strong>${esc(b.name)}</strong><small>${esc(b.month)} · ${money(b.amount)}</small></div><button class="danger-btn" type="button" data-delete-budget="${esc(b.id)}">Delete</button></div>`).join('')||empty('No budgets')}
function renderTheme(){const dark=state.settings.theme==='dark';document.body.classList.toggle('dark',dark);$('switchTheme').classList.toggle('on',dark);$('themeToggle').textContent=dark?'☀':'☾'}
function addTransaction(e){e.preventDefault();const amount=num($('amount').value),date=$('date').value,note=$('note').value.trim(),type=state.currentType;if(!amount||amount<=0)return toast('Enter an amount greater than zero');if(!date)return toast('Choose a date');const t={id:uid('tx'),type:type==='loan'?'income':type==='payback'?'expense':type,amount,date,note,category:type==='loan'?'Loan':type==='payback'?'Loan Repayment':$('category').value,loanId:'',createdAt:new Date().toISOString()};if(type==='loan'){t.loanId=uid('loan');state.loans.push({id:t.loanId,name:note||'Loan',principal:amount,remaining:amount,date,note,createdAt:t.createdAt})}if(type==='payback'){const l=state.loans.find(x=>String(x.id)===String($('loanSelect').value));if(!l)return toast('Select an active loan');if(amount>l.remaining)return toast('Payback cannot exceed remaining loan');t.loanId=l.id}state.transactions.push(t);save();e.target.reset();$('date').value=today;render();toast(type==='loan'?'Loan recorded as income':type==='payback'?'Payback deducted from loan':'Transaction saved')}
function addBudget(e){e.preventDefault();const name=$('budgetCategory').value,amount=num($('budgetAmount').value),m=$('budgetMonth').value,threshold=num($('budgetThreshold').value)||80;if(!name||!amount||!m)return toast('Category, amount and month are required');if(threshold<1||threshold>100)return toast('Threshold must be 1–100');const old=state.budgets.find(b=>b.name===name&&b.month===m);if(old)Object.assign(old,{amount,threshold,dueDate:$('budgetDueDate').value});else state.budgets.push({id:uid('budget'),name,amount,threshold,dueDate:$('budgetDueDate').value,month:m,createdAt:new Date().toISOString()});state.reportMonth=m;save();render();toast(old?'Budget updated':'Budget saved')}
function resetMonth(){const m=$('budgetMonth').value||month();if(!confirm(`Delete all budgets for ${m}?`))return;state.budgets=state.budgets.filter(b=>b.month!==m);save();render();toast('Monthly budgets reset')}
async function api(action,payload={}){if(!state.settings.syncUrl)throw Error('Enter the Apps Script URL first');const r=await fetch(state.settings.syncUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||'Sync failed');return x.data||x}
async function sync(mode){if(syncing)return;syncing=true;try{if(mode==='pull'){const d=await api('getAll');state.transactions=d.transactions||[];state.categories=d.categories?.length?d.categories:state.categories;state.budgets=d.budgets||[];state.goals=d.goals||[];state.loans=d.loans||[];state.settings.syncRevision=d.revision||'';state.settings.lastSynced=new Date().toISOString();save();render();toast('Pulled from Google Sheets')}else if(mode==='test'){await api('status');toast('Connection successful')}else{const d=await api('replaceAll',state);state.settings.syncRevision=d.revision||'';state.settings.lastSynced=new Date().toISOString();save();toast('Pushed to Google Sheets')}}catch(e){toast(e.message)}finally{syncing=false}}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`moneyflow-${today}.json`;a.click();URL.revokeObjectURL(a.href)}
function bind(){document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p)return show(p.dataset.page);const tab=e.target.closest('[data-type]');if(tab)return setType(tab.dataset.type);if(e.target.id==='themeToggle'||e.target.id==='switchTheme'){state.settings.theme=state.settings.theme==='dark'?'light':'dark';save();renderTheme()}if(e.target.id==='addBudgetBtn')$('budgetForm').requestSubmit();if(e.target.id==='resetMonthBtn')resetMonth();if(e.target.id==='clearTransactionsBtn'&&confirm('Clear all transactions and loans?')){state.transactions=[];state.loans=[];save();render();toast('Transactions cleared')}const dt=e.target.closest('[data-delete-tx]');if(dt){state.transactions=state.transactions.filter(t=>String(t.id)!==String(dt.dataset.deleteTx));rebuildLoans(state);save();render();toast('Transaction deleted')}const db=e.target.closest('[data-delete-budget]');if(db){state.budgets=state.budgets.filter(b=>String(b.id)!==String(db.dataset.deleteBudget));save();render();toast('Budget deleted')}const dc=e.target.closest('[data-delete-cat]');if(dc){const c=state.categories[Number(dc.dataset.deleteCat)];if(state.transactions.some(t=>t.category===c.name)||state.budgets.some(b=>b.name===c.name))return toast('Category is in use');state.categories.splice(Number(dc.dataset.deleteCat),1);save();render();toast('Category deleted')}});document.addEventListener('change',e=>{if(e.target.id==='monthSelect'){state.reportMonth=e.target.value;save();render()}if(e.target.id==='syncUrl'){state.settings.syncUrl=e.target.value.trim();save()}if(e.target.id==='importData'&&e.target.files[0]){const r=new FileReader();r.onload=()=>{try{state=normalize(JSON.parse(r.result));save();render();toast('Data imported')}catch(_){toast('Invalid JSON file')}};r.readAsText(e.target.files[0])}});$('transactionForm').addEventListener('submit',addTransaction);$('budgetForm').addEventListener('submit',addBudget);$('categoryForm').addEventListener('submit',e=>{e.preventDefault();const name=$('newCategory').value.trim(),type=$('newCategoryType').value;if(!name)return toast('Enter a category name');if(state.categories.some(c=>c.name.toLowerCase()===name.toLowerCase()&&c.type===type))return toast('Category already exists');state.categories.push({name,type,createdAt:new Date().toISOString()});$('newCategory').value='';save();render();toast('Category added')});$('testSync').onclick=()=>sync('test');$('pullSync').onclick=()=>sync('pull');$('pushSync').onclick=()=>sync('push');$('exportData').onclick=download}
$('date').value=today;$('budgetMonth').value=currentMonth;bind();setType('expense');render();
})();
