(() => {
'use strict';
const $=id=>document.getElementById(id);
function toast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.add('on');clearTimeout(el._polishTimer);el._polishTimer=setTimeout(()=>el.classList.remove('on'),2600)}
function decorateGreeting(){const h=new Date().getHours();const data=h<5?['Good night','🌙']:h<12?['Good morning','🌅']:h<18?['Good afternoon','☀️']:['Good evening','🌆'];const title=$('greetTitle');if(title){title.textContent=`${data[1]} ${data[0]}`;title.setAttribute('aria-label',data[0]);title.dataset.greetingApplied='true'}}
function drawerNav(){const nav=$('mobileNav');if(!nav||nav.dataset.drawerReady)return;nav.dataset.drawerReady='true';nav.setAttribute('aria-expanded','false');nav.addEventListener('click',e=>{if(e.target===nav){const open=nav.classList.toggle('is-open');nav.setAttribute('aria-expanded',String(open));return}const button=e.target.closest('.nav-btn');if(button){nav.classList.remove('is-open');nav.setAttribute('aria-expanded','false')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('is-open')){nav.classList.remove('is-open');nav.setAttribute('aria-expanded','false')}})}
function enhanceFields(){document.querySelectorAll('input,select,button').forEach(el=>{if(!el.getAttribute('aria-label')&&!el.labels?.length&&el.textContent.trim())el.setAttribute('aria-label',el.textContent.trim())});['amount','date','category','budgetCategory','budgetAmount','budgetMonth','syncUrl'].forEach(id=>{const el=$(id);if(el)el.setAttribute('aria-required','true')});const url=$('syncUrl');if(url){url.addEventListener('blur',()=>{if(url.value&&!/^https:\/\//i.test(url.value)){url.setCustomValidity('Use a secure https:// Apps Script URL.');toast('Sync URL must start with https://')}else url.setCustomValidity('')})}}
function observeDynamicContent(){const alertHost=$('budgetAlerts');if(alertHost){new MutationObserver(()=>{alertHost.querySelectorAll('.alert').forEach(el=>{el.setAttribute('role','status');el.setAttribute('tabindex','0')})}).observe(alertHost,{childList:true})}const table=$('transactionRows');if(table){new MutationObserver(()=>{table.querySelectorAll('tr').forEach(row=>row.setAttribute('tabindex','0'))}).observe(table,{childList:true})}}
function focusManagement(){document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(!page)return;requestAnimationFrame(()=>{const target=$(page.dataset.page);target?.querySelector('h2,h1')?.focus?.()})});document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const el=document.activeElement;if(el?.classList.contains('nav-btn')||el?.classList.contains('tab')){e.preventDefault();el.click()}})}
function run(){decorateGreeting();drawerNav();enhanceFields();observeDynamicContent();focusManagement();window.setInterval(decorateGreeting,60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
