(() => {
'use strict';
const KEY='moneyflow-v3';const $=id=>document.getElementById(id);const today=new Date().toISOString().slice(0,10);let page=1;const pageSize=50;
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}}
function escape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(v){return `${Math.round(Number(v)||0).toLocaleString()} MMK`}
function greeting(){const h=new Date().getHours();const data=h<5?['Good night','🌙']:h<12?['Good morning','🌅']:h<18?['Good afternoon','☀️']:['Good evening','🌆'];const title=$('greetTitle');if(title&&!title.dataset.greetingApplied){title.dataset.greetingApplied='1';title.textContent=`${data[1]} ${data[0]}`}}
function enhanceTransactions(){const host=$('transactionToolbar'),body=$('transactionRows');if(!host||!body||host.dataset.ready)return;host.dataset.ready='1';const prev=document.createElement('button'),next=document.createElement('button');prev.type=next.type='button';prev.className=next.className='ghost-btn';prev.textContent='← Newer';next.textContent='Older →';host.append(prev,next);function draw(){const s=state();const rows=(Array.isArray(s.transactions)?s.transactions:[]).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));const pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages);const visible=rows.slice((page-1)*pageSize,page*pageSize);body.innerHTML=visible.map(t=>`<tr><td>${escape(t.date)}</td><td>${escape(t.type)}</td><td>${escape(t.category)}</td><td>${escape(t.note||'-')}</td><td>${money(t.amount)}</td><td></td></tr>`).join('')||'<tr><td colspan="6">No transactions</td></tr>';prev.disabled=page<=1;next.disabled=page>=pages;host.setAttribute('aria-label',`Page ${page} of ${pages}`);const count=$('transactionCount');if(count)count.textContent=`${rows.length} records · page ${page}/${pages}`};prev.onclick=()=>{page--;draw()};next.onclick=()=>{page++;draw()};const observer=new MutationObserver(draw);observer.observe(body,{childList:true});draw()}
function run(){greeting();enhanceTransactions();const status=$('syncStatus');if(status){const s=state();status.textContent=s.settings&&s.settings.lastSynced?`Last synced ${new Date(s.settings.lastSynced).toLocaleString()}`:'Local data only — sync is manual';}document.addEventListener('click',e=>{if(e.target.closest('#pullSync,#pushSync,#testSync'))setTimeout(()=>{const s=state();if(status)status.textContent=s.settings&&s.settings.lastSynced?`Last synced ${new Date(s.settings.lastSynced).toLocaleString()}`:'Sync complete';},700)},{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
