const SPREADSHEET_ID = '';
const TRANSACTION_HEADERS = ['id','type','amount','date','category','note','loanId','createdAt'];
const CATEGORY_HEADERS = ['name','type','createdAt'];
const BUDGET_HEADERS = ['id','name','amount','threshold','month','dueDate','createdAt'];
const GOAL_HEADERS = ['name','target','saved'];
const LOAN_HEADERS = ['id','name','principal','remaining','date','note','createdAt'];
function ss(){return SPREADSHEET_ID?SpreadsheetApp.openById(SPREADSHEET_ID):SpreadsheetApp.getActiveSpreadsheet()}
function json(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON)}
function doGet(e){try{const a=e&&e.parameter?e.parameter.action:'';if(a==='getAll')return json({ok:true,data:readAll()});if(a==='status')return json({ok:true,data:status()});return json({ok:true,message:'MoneyFlow API is running'})}catch(err){return json({ok:false,error:String(err.message||err)})}}
function doPost(e){try{const r=JSON.parse(e&&e.postData&&e.postData.contents||'{}');if(r.action==='getAll')return json({ok:true,data:readAll()});if(r.action==='status')return json({ok:true,data:status()});if(r.action==='replaceAll'||r.action==='writeAll')return json({ok:true,data:writeAll(r)});return json({ok:false,error:'Unknown action'})}catch(err){return json({ok:false,error:String(err.message||err)})}}
function sheet(n,h){const s=ss().getSheetByName(n)||ss().insertSheet(n);if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1);return s}
function rows(n,h){const v=sheet(n,h).getDataRange().getValues();return v.length<2?[]:v.slice(1).filter(r=>r.some(x=>x!=='')).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o})}
function writeTable(n,h,values){const s=sheet(n,h);s.clearContents();s.getRange(1,1,1,h.length).setValues([h]);if(values.length)s.getRange(2,1,values.length,h.length).setValues(values);s.setFrozenRows(1)}
function num(v){const n=Number(String(v??'').replace(/,/g,''));return isFinite(n)?n:0}function iso(v){const d=v?new Date(v):new Date();return isNaN(d.getTime())?new Date().toISOString():d.toISOString()}function date(v){if(Object.prototype.toString.call(v)==='[object Date]')return Utilities.formatDate(v,Session.getScriptTimeZone(),'yyyy-MM-dd');const s=String(v||'');return /^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd')}
function tx(v){v=v||{};let type=String(v.type||'expense'),cat=String(v.category||'General').trim();if(type==='loan'||['loan','loan received'].includes(cat.toLowerCase())){type='income';cat='Loan'}if(['loan repayment','loan payback'].includes(cat.toLowerCase())){type='expense';cat='Loan Repayment'}return {id:String(v.id||Utilities.getUuid()),type,amount:num(v.amount),date:date(v.date),category:cat,note:String(v.note||''),loanId:String(v.loanId||''),createdAt:iso(v.createdAt)}}
function category(v){v=v||{};return {name:String(v.name||'').trim(),type:String(v.type||'expense'),createdAt:iso(v.createdAt)}}function budget(v){v=v||{};return {id:String(v.id||Utilities.getUuid()),name:String(v.name||v.category||'').trim(),amount:num(v.amount),threshold:num(v.threshold)||80,month:String(v.month||''),dueDate:String(v.dueDate||''),createdAt:iso(v.createdAt)}}function loan(v){v=v||{};return {id:String(v.id||Utilities.getUuid()),name:String(v.name||'Loan'),principal:num(v.principal||v.amount),remaining:num(v.remaining),date:date(v.date),note:String(v.note||''),createdAt:iso(v.createdAt)}}
function unique(a){const out=[];(a||[]).map(category).filter(x=>x.name).forEach(x=>{if(!out.some(y=>y.name.toLowerCase()===x.name.toLowerCase()&&y.type===x.type))out.push(x)});return out}
function calculateLoans(loans,transactions){const out=loans.slice();transactions.filter(t=>t.type==='income'&&t.loanId).forEach(t=>{if(!out.some(l=>String(l.id)===String(t.loanId)))out.push(loan({id:t.loanId,name:t.note||'Loan',principal:t.amount,remaining:t.amount,date:t.date,note:t.note,createdAt:t.createdAt}))});return out.map(l=>{const received=transactions.filter(t=>t.type==='income'&&String(t.loanId)===String(l.id)).reduce((a,t)=>a+num(t.amount),0),paid=transactions.filter(t=>t.type==='expense'&&String(t.loanId)===String(l.id)).reduce((a,t)=>a+num(t.amount),0);return {...l,principal:received||l.principal,remaining:Math.max(0,(received||l.principal)-paid)}})}
function readAll(){const transactions=rows('Transactions',TRANSACTION_HEADERS).map(tx),categories=unique(rows('Categories',CATEGORY_HEADERS)),budgets=rows('Budgets',BUDGET_HEADERS).map(budget).filter(x=>x.name&&x.month),goals=rows('Goals',GOAL_HEADERS),loans=calculateLoans(rows('Loans',LOAN_HEADERS).map(loan),transactions),data={transactions,categories,budgets,goals,loans};data.revision=Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.MD5,JSON.stringify(data),Utilities.Charset.UTF_8));return data}
function status(){const d=readAll();return {revision:d.revision,count:d.transactions.length,categoryCount:d.categories.length,budgetCount:d.budgets.length,loanCount:d.loans.length}}
function writeAll(p){const transactions=(p.transactions||[]).map(tx),categories=unique(p.categories||[]),budgets=(p.budgets||[]).map(budget).filter(x=>x.name&&x.month),goals=p.goals||[],loans=calculateLoans((p.loans||[]).map(loan),transactions);writeTable('Transactions',TRANSACTION_HEADERS,transactions.map(x=>[x.id,x.type,x.amount,x.date,x.category,x.note,x.loanId,x.createdAt]));writeTable('Categories',CATEGORY_HEADERS,categories.map(x=>[x.name,x.type,x.createdAt]));writeTable('Budgets',BUDGET_HEADERS,budgets.map(x=>[x.id,x.name,x.amount,x.threshold,x.month,x.dueDate,x.createdAt]));writeTable('Goals',GOAL_HEADERS,goals.map(x=>[x.name,x.target||0,x.saved||0]));writeTable('Loans',LOAN_HEADERS,loans.map(x=>[x.id,x.name,x.principal,x.remaining,x.date,x.note,x.createdAt]));return readAll()}
