const SPREADSHEET_ID = '';
const TRANSACTION_HEADERS = ['id','type','amount','date','category','note','loanId','createdAt'];
const CATEGORY_HEADERS = ['name','type','createdAt'];
const BUDGET_HEADERS = ['id','name','amount','threshold','month','dueDate','createdAt'];
const GOAL_HEADERS = ['name','target','saved'];
const LOAN_HEADERS = ['id','name','principal','remaining','date','note','createdAt'];

function ss(){return SPREADSHEET_ID ? SpreadsheetApp.openById(SPREADSHEET_ID) : SpreadsheetApp.getActiveSpreadsheet();}
function json(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
function doGet(e){try{const action=e&&e.parameter?e.parameter.action:'';if(action==='status')return json({ok:true,data:status()});if(action==='getAll')return json({ok:true,data:readAll()});return json({ok:true,message:'MoneyFlow API is running'});}catch(error){return json({ok:false,error:String(error.message||error)});}}
function doPost(e){try{const request=JSON.parse(e&&e.postData&&e.postData.contents||'{}');if(request.action==='status')return json({ok:true,data:status()});if(request.action==='getAll')return json({ok:true,data:readAll()});if(request.action==='replaceAll'||request.action==='writeAll')return json({ok:true,data:writeAll(request)});return json({ok:false,error:'Unknown action'});}catch(error){return json({ok:false,error:String(error.message||error)});}}
function sheet(name,headers){const target=ss().getSheetByName(name)||ss().insertSheet(name);if(target.getLastRow()===0)target.getRange(1,1,1,headers.length).setValues([headers]);target.setFrozenRows(1);return target;}
function rows(name,headers){const values=sheet(name,headers).getDataRange().getValues();if(values.length<2)return [];return values.slice(1).filter(row=>row.some(value=>value!==''&&value!==null)).map(row=>{const item={};headers.forEach((header,index)=>item[header]=row[index]);return item;});}
function writeTable(name,headers,values){const target=sheet(name,headers);target.clearContents();target.getRange(1,1,1,headers.length).setValues([headers]);if(values.length)target.getRange(2,1,values.length,headers.length).setValues(values);target.setFrozenRows(1);}
function num(value){const result=Number(String(value==null?'':value).replace(/,/g,''));return isFinite(result)?result:0;}
function today(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd');}
function iso(value){const date=value?new Date(value):new Date();return isNaN(date.getTime())?new Date().toISOString():date.toISOString();}
function formatDate(value){if(Object.prototype.toString.call(value)==='[object Date]')return Utilities.formatDate(value,Session.getScriptTimeZone(),'yyyy-MM-dd');const text=String(value||'');return /^\d{4}-\d{2}-\d{2}/.test(text)?text.slice(0,10):today();}
function normalizeTransaction(value){const item=value||{};let type=String(item.type||'expense'),category=String(item.category||'General').trim();if(type==='loan'||['loan','loan received'].includes(category.toLowerCase())){type='income';category='Loan';}if(['loan repayment','loan payback'].includes(category.toLowerCase())){type='expense';category='Loan Repayment';}return {id:String(item.id||Utilities.getUuid()),type,amount:num(item.amount),date:formatDate(item.date),category,note:String(item.note||''),loanId:String(item.loanId||''),createdAt:iso(item.createdAt)};}
function normalizeCategory(value){const item=value||{};return {name:String(item.name||'').trim(),type:String(item.type||'expense'),createdAt:iso(item.createdAt)};}
function normalizeBudget(value){const item=value||{};return {id:String(item.id||Utilities.getUuid()),name:String(item.name||item.category||'').trim(),amount:num(item.amount),threshold:num(item.threshold)||80,month:String(item.month||''),dueDate:String(item.dueDate||''),createdAt:iso(item.createdAt)};}
function normalizeGoal(value){const item=value||{};return {name:String(item.name||'').trim(),target:num(item.target),saved:num(item.saved)};}
function normalizeLoan(value){const item=value||{},principal=num(item.principal||item.amount);return {id:String(item.id||Utilities.getUuid()),name:String(item.name||'Loan').trim(),principal,remaining:Math.max(0,num(item.remaining===undefined?principal:item.remaining)),date:formatDate(item.date),note:String(item.note||''),createdAt:iso(item.createdAt)};}
function uniqueCategories(values){const result=[];(values||[]).map(normalizeCategory).filter(item=>item.name).forEach(item=>{if(!result.some(existing=>existing.name.toLowerCase()===item.name.toLowerCase()&&existing.type===item.type))result.push(item);});return result;}
function calculateLoans(loans,transactions){const result=loans.slice();transactions.filter(tx=>tx.type==='income'&&tx.loanId).forEach(tx=>{if(!result.some(loan=>String(loan.id)===String(tx.loanId)))result.push(normalizeLoan({id:tx.loanId,name:tx.note||'Loan',principal:tx.amount,remaining:tx.amount,date:tx.date,note:tx.note,createdAt:tx.createdAt}));});return result.map(loan=>{const received=transactions.filter(tx=>tx.type==='income'&&String(tx.loanId)===String(loan.id)).reduce((sum,tx)=>sum+num(tx.amount),0);const paid=transactions.filter(tx=>tx.type==='expense'&&String(tx.loanId)===String(loan.id)).reduce((sum,tx)=>sum+num(tx.amount),0);return Object.assign({},loan,{principal:received||loan.principal,remaining:Math.max(0,(received||loan.principal)-paid)});});}
function readAll(){const transactions=rows('Transactions',TRANSACTION_HEADERS).map(normalizeTransaction),categories=uniqueCategories(rows('Categories',CATEGORY_HEADERS)),budgets=rows('Budgets',BUDGET_HEADERS).map(normalizeBudget).filter(item=>item.name&&item.month),goals=rows('Goals',GOAL_HEADERS).map(normalizeGoal).filter(item=>item.name),loans=calculateLoans(rows('Loans',LOAN_HEADERS).map(normalizeLoan),transactions),data={transactions,categories,budgets,goals,loans};data.revision=Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.MD5,JSON.stringify(data),Utilities.Charset.UTF_8));return data;}
function status(){const names=[['Transactions',TRANSACTION_HEADERS],['Categories',CATEGORY_HEADERS],['Budgets',BUDGET_HEADERS],['Goals',GOAL_HEADERS],['Loans',LOAN_HEADERS]],meta={};names.forEach(pair=>{const target=ss().getSheetByName(pair[0]);meta[pair[0]]={rows:target?Math.max(0,target.getLastRow()-1):0};});return {meta,serverTime:new Date().toISOString()};}
function writeAll(payload){const transactions=(payload.transactions||[]).map(normalizeTransaction),categories=uniqueCategories(payload.categories||[]),budgets=(payload.budgets||[]).map(normalizeBudget).filter(item=>item.name&&item.month),goals=(payload.goals||[]).map(normalizeGoal).filter(item=>item.name),loans=calculateLoans((payload.loans||[]).map(normalizeLoan),transactions);writeTable('Transactions',TRANSACTION_HEADERS,transactions.map(item=>[item.id,item.type,item.amount,item.date,item.category,item.note,item.loanId,item.createdAt]));writeTable('Categories',CATEGORY_HEADERS,categories.map(item=>[item.name,item.type,item.createdAt]));writeTable('Budgets',BUDGET_HEADERS,budgets.map(item=>[item.id,item.name,item.amount,item.threshold,item.month,item.dueDate,item.createdAt]));writeTable('Goals',GOAL_HEADERS,goals.map(item=>[item.name,item.target,item.saved]));writeTable('Loans',LOAN_HEADERS,loans.map(item=>[item.id,item.name,item.principal,item.remaining,item.date,item.note,item.createdAt]));return readAll();}
